/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZaioRouteImport } from './routes/zaio'
import { Route as XRouteImport } from './routes/x'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PaypalRouteImport } from './routes/paypal'
import { Route as GithubRouteImport } from './routes/github'
import { Route as ContributorsRouteImport } from './routes/contributors'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const ZaioRoute = ZaioRouteImport.update({
  id: '/zaio',
  path: '/zaio',
  getParentRoute: () => rootRouteImport,
} as any)
const XRoute = XRouteImport.update({
  id: '/x',
  path: '/x',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PaypalRoute = PaypalRouteImport.update({
  id: '/paypal',
  path: '/paypal',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubRoute = GithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributorsRoute = ContributorsRouteImport.update({
  id: '/contributors',
  path: '/contributors',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contributors': typeof ContributorsRoute
  '/github': typeof GithubRoute
  '/paypal': typeof PaypalRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/whatsapp': typeof WhatsappRoute
  '/x': typeof XRoute
  '/zaio': typeof ZaioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contributors': typeof ContributorsRoute
  '/github': typeof GithubRoute
  '/paypal': typeof PaypalRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/whatsapp': typeof WhatsappRoute
  '/x': typeof XRoute
  '/zaio': typeof ZaioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contributors': typeof ContributorsRoute
  '/github': typeof GithubRoute
  '/paypal': typeof PaypalRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/whatsapp': typeof WhatsappRoute
  '/x': typeof XRoute
  '/zaio': typeof ZaioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contributors'
    | '/github'
    | '/paypal'
    | '/privacy'
    | '/terms'
    | '/whatsapp'
    | '/x'
    | '/zaio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contributors'
    | '/github'
    | '/paypal'
    | '/privacy'
    | '/terms'
    | '/whatsapp'
    | '/x'
    | '/zaio'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contributors'
    | '/github'
    | '/paypal'
    | '/privacy'
    | '/terms'
    | '/whatsapp'
    | '/x'
    | '/zaio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContributorsRoute: typeof ContributorsRoute
  GithubRoute: typeof GithubRoute
  PaypalRoute: typeof PaypalRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  WhatsappRoute: typeof WhatsappRoute
  XRoute: typeof XRoute
  ZaioRoute: typeof ZaioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zaio': {
      id: '/zaio'
      path: '/zaio'
      fullPath: '/zaio'
      preLoaderRoute: typeof ZaioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/x': {
      id: '/x'
      path: '/x'
      fullPath: '/x'
      preLoaderRoute: typeof XRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paypal': {
      id: '/paypal'
      path: '/paypal'
      fullPath: '/paypal'
      preLoaderRoute: typeof PaypalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github': {
      id: '/github'
      path: '/github'
      fullPath: '/github'
      preLoaderRoute: typeof GithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contributors': {
      id: '/contributors'
      path: '/contributors'
      fullPath: '/contributors'
      preLoaderRoute: typeof ContributorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContributorsRoute: ContributorsRoute,
  GithubRoute: GithubRoute,
  PaypalRoute: PaypalRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  WhatsappRoute: WhatsappRoute,
  XRoute: XRoute,
  ZaioRoute: ZaioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
