/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as infoIndexRouteImport } from './routes/(info)/index'
import { Route as infoZaioRouteImport } from './routes/(info)/zaio'
import { Route as infoXRouteImport } from './routes/(info)/x'
import { Route as infoWhatsappRouteImport } from './routes/(info)/whatsapp'
import { Route as infoTermsRouteImport } from './routes/(info)/terms'
import { Route as infoPrivacyRouteImport } from './routes/(info)/privacy'
import { Route as infoPaypalRouteImport } from './routes/(info)/paypal'
import { Route as infoGithubRouteImport } from './routes/(info)/github'
import { Route as infoContributorsRouteImport } from './routes/(info)/contributors'
import { Route as infoAboutRouteImport } from './routes/(info)/about'

const infoIndexRoute = infoIndexRouteImport.update({
  id: '/(info)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const infoZaioRoute = infoZaioRouteImport.update({
  id: '/(info)/zaio',
  path: '/zaio',
  getParentRoute: () => rootRouteImport,
} as any)
const infoXRoute = infoXRouteImport.update({
  id: '/(info)/x',
  path: '/x',
  getParentRoute: () => rootRouteImport,
} as any)
const infoWhatsappRoute = infoWhatsappRouteImport.update({
  id: '/(info)/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const infoTermsRoute = infoTermsRouteImport.update({
  id: '/(info)/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const infoPrivacyRoute = infoPrivacyRouteImport.update({
  id: '/(info)/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const infoPaypalRoute = infoPaypalRouteImport.update({
  id: '/(info)/paypal',
  path: '/paypal',
  getParentRoute: () => rootRouteImport,
} as any)
const infoGithubRoute = infoGithubRouteImport.update({
  id: '/(info)/github',
  path: '/github',
  getParentRoute: () => rootRouteImport,
} as any)
const infoContributorsRoute = infoContributorsRouteImport.update({
  id: '/(info)/contributors',
  path: '/contributors',
  getParentRoute: () => rootRouteImport,
} as any)
const infoAboutRoute = infoAboutRouteImport.update({
  id: '/(info)/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/about': typeof infoAboutRoute
  '/contributors': typeof infoContributorsRoute
  '/github': typeof infoGithubRoute
  '/paypal': typeof infoPaypalRoute
  '/privacy': typeof infoPrivacyRoute
  '/terms': typeof infoTermsRoute
  '/whatsapp': typeof infoWhatsappRoute
  '/x': typeof infoXRoute
  '/zaio': typeof infoZaioRoute
  '/': typeof infoIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof infoAboutRoute
  '/contributors': typeof infoContributorsRoute
  '/github': typeof infoGithubRoute
  '/paypal': typeof infoPaypalRoute
  '/privacy': typeof infoPrivacyRoute
  '/terms': typeof infoTermsRoute
  '/whatsapp': typeof infoWhatsappRoute
  '/x': typeof infoXRoute
  '/zaio': typeof infoZaioRoute
  '/': typeof infoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(info)/about': typeof infoAboutRoute
  '/(info)/contributors': typeof infoContributorsRoute
  '/(info)/github': typeof infoGithubRoute
  '/(info)/paypal': typeof infoPaypalRoute
  '/(info)/privacy': typeof infoPrivacyRoute
  '/(info)/terms': typeof infoTermsRoute
  '/(info)/whatsapp': typeof infoWhatsappRoute
  '/(info)/x': typeof infoXRoute
  '/(info)/zaio': typeof infoZaioRoute
  '/(info)/': typeof infoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/about'
    | '/contributors'
    | '/github'
    | '/paypal'
    | '/privacy'
    | '/terms'
    | '/whatsapp'
    | '/x'
    | '/zaio'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/contributors'
    | '/github'
    | '/paypal'
    | '/privacy'
    | '/terms'
    | '/whatsapp'
    | '/x'
    | '/zaio'
    | '/'
  id:
    | '__root__'
    | '/(info)/about'
    | '/(info)/contributors'
    | '/(info)/github'
    | '/(info)/paypal'
    | '/(info)/privacy'
    | '/(info)/terms'
    | '/(info)/whatsapp'
    | '/(info)/x'
    | '/(info)/zaio'
    | '/(info)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  infoAboutRoute: typeof infoAboutRoute
  infoContributorsRoute: typeof infoContributorsRoute
  infoGithubRoute: typeof infoGithubRoute
  infoPaypalRoute: typeof infoPaypalRoute
  infoPrivacyRoute: typeof infoPrivacyRoute
  infoTermsRoute: typeof infoTermsRoute
  infoWhatsappRoute: typeof infoWhatsappRoute
  infoXRoute: typeof infoXRoute
  infoZaioRoute: typeof infoZaioRoute
  infoIndexRoute: typeof infoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(info)/': {
      id: '/(info)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof infoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(info)/zaio': {
      id: '/(info)/zaio'
      path: '/zaio'
      fullPath: '/zaio'
      preLoaderRoute: typeof infoZaioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(info)/x': {
      id: '/(info)/x'
      path: '/x'
      fullPath: '/x'
      preLoaderRoute: typeof infoXRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(info)/whatsapp': {
      id: '/(info)/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof infoWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(info)/terms': {
      id: '/(info)/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof infoTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(info)/privacy': {
      id: '/(info)/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof infoPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(info)/paypal': {
      id: '/(info)/paypal'
      path: '/paypal'
      fullPath: '/paypal'
      preLoaderRoute: typeof infoPaypalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(info)/github': {
      id: '/(info)/github'
      path: '/github'
      fullPath: '/github'
      preLoaderRoute: typeof infoGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(info)/contributors': {
      id: '/(info)/contributors'
      path: '/contributors'
      fullPath: '/contributors'
      preLoaderRoute: typeof infoContributorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(info)/about': {
      id: '/(info)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof infoAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  infoAboutRoute: infoAboutRoute,
  infoContributorsRoute: infoContributorsRoute,
  infoGithubRoute: infoGithubRoute,
  infoPaypalRoute: infoPaypalRoute,
  infoPrivacyRoute: infoPrivacyRoute,
  infoTermsRoute: infoTermsRoute,
  infoWhatsappRoute: infoWhatsappRoute,
  infoXRoute: infoXRoute,
  infoZaioRoute: infoZaioRoute,
  infoIndexRoute: infoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
