/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as infoIndexRouteImport } from './routes/(info)/index'
import { Route as AuthAuthRouteImport } from './routes/_auth/auth'
import { Route as AppTasksRouteImport } from './routes/_app/tasks'
import { Route as AppProjectsRouteImport } from './routes/_app/projects'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as infoZaioRouteImport } from './routes/(info)/zaio'
import { Route as infoXRouteImport } from './routes/(info)/x'
import { Route as infoWhatsappRouteImport } from './routes/(info)/whatsapp'
import { Route as infoTermsRouteImport } from './routes/(info)/terms'
import { Route as infoRoadmapRouteImport } from './routes/(info)/roadmap'
import { Route as infoPrivacyRouteImport } from './routes/(info)/privacy'
import { Route as infoPaypalRouteImport } from './routes/(info)/paypal'
import { Route as infoGithubRouteImport } from './routes/(info)/github'
import { Route as infoCreditRouteImport } from './routes/(info)/credit'
import { Route as infoContributorsRouteImport } from './routes/(info)/contributors'
import { Route as infoAboutRouteImport } from './routes/(info)/about'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const infoIndexRoute = infoIndexRouteImport.update({
  id: '/(info)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAuthRoute = AuthAuthRouteImport.update({
  id: '/_auth/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const infoZaioRoute = infoZaioRouteImport.update({
  id: '/(info)/zaio',
  path: '/zaio',
  getParentRoute: () => rootRouteImport,
} as any)
const infoXRoute = infoXRouteImport.update({
  id: '/(info)/x',
  path: '/x',
  getParentRoute: () => rootRouteImport,
} as any)
const infoWhatsappRoute = infoWhatsappRouteImport.update({
  id: '/(info)/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const infoTermsRoute = infoTermsRouteImport.update({
  id: '/(info)/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const infoRoadmapRoute = infoRoadmapRouteImport.update({
  id: '/(info)/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const infoPrivacyRoute = infoPrivacyRouteImport.update({
  id: '/(info)/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const infoPaypalRoute = infoPaypalRouteImport.update({
  id: '/(info)/paypal',
  path: '/paypal',
  getParentRoute: () => rootRouteImport,
} as any)
const infoGithubRoute = infoGithubRouteImport.update({
  id: '/(info)/github',
  path: '/github',
  getParentRoute: () => rootRouteImport,
} as any)
const infoCreditRoute = infoCreditRouteImport.update({
  id: '/(info)/credit',
  path: '/credit',
  getParentRoute: () => rootRouteImport,
} as any)
const infoContributorsRoute = infoContributorsRouteImport.update({
  id: '/(info)/contributors',
  path: '/contributors',
  getParentRoute: () => rootRouteImport,
} as any)
const infoAboutRoute = infoAboutRouteImport.update({
  id: '/(info)/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/about': typeof infoAboutRoute
  '/contributors': typeof infoContributorsRoute
  '/credit': typeof infoCreditRoute
  '/github': typeof infoGithubRoute
  '/paypal': typeof infoPaypalRoute
  '/privacy': typeof infoPrivacyRoute
  '/roadmap': typeof infoRoadmapRoute
  '/terms': typeof infoTermsRoute
  '/whatsapp': typeof infoWhatsappRoute
  '/x': typeof infoXRoute
  '/zaio': typeof infoZaioRoute
  '/dashboard': typeof AppDashboardRoute
  '/projects': typeof AppProjectsRoute
  '/tasks': typeof AppTasksRoute
  '/auth': typeof AuthAuthRoute
  '/': typeof infoIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof infoAboutRoute
  '/contributors': typeof infoContributorsRoute
  '/credit': typeof infoCreditRoute
  '/github': typeof infoGithubRoute
  '/paypal': typeof infoPaypalRoute
  '/privacy': typeof infoPrivacyRoute
  '/roadmap': typeof infoRoadmapRoute
  '/terms': typeof infoTermsRoute
  '/whatsapp': typeof infoWhatsappRoute
  '/x': typeof infoXRoute
  '/zaio': typeof infoZaioRoute
  '/dashboard': typeof AppDashboardRoute
  '/projects': typeof AppProjectsRoute
  '/tasks': typeof AppTasksRoute
  '/auth': typeof AuthAuthRoute
  '/': typeof infoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/(info)/about': typeof infoAboutRoute
  '/(info)/contributors': typeof infoContributorsRoute
  '/(info)/credit': typeof infoCreditRoute
  '/(info)/github': typeof infoGithubRoute
  '/(info)/paypal': typeof infoPaypalRoute
  '/(info)/privacy': typeof infoPrivacyRoute
  '/(info)/roadmap': typeof infoRoadmapRoute
  '/(info)/terms': typeof infoTermsRoute
  '/(info)/whatsapp': typeof infoWhatsappRoute
  '/(info)/x': typeof infoXRoute
  '/(info)/zaio': typeof infoZaioRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/projects': typeof AppProjectsRoute
  '/_app/tasks': typeof AppTasksRoute
  '/_auth/auth': typeof AuthAuthRoute
  '/(info)/': typeof infoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/about'
    | '/contributors'
    | '/credit'
    | '/github'
    | '/paypal'
    | '/privacy'
    | '/roadmap'
    | '/terms'
    | '/whatsapp'
    | '/x'
    | '/zaio'
    | '/dashboard'
    | '/projects'
    | '/tasks'
    | '/auth'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/contributors'
    | '/credit'
    | '/github'
    | '/paypal'
    | '/privacy'
    | '/roadmap'
    | '/terms'
    | '/whatsapp'
    | '/x'
    | '/zaio'
    | '/dashboard'
    | '/projects'
    | '/tasks'
    | '/auth'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/(info)/about'
    | '/(info)/contributors'
    | '/(info)/credit'
    | '/(info)/github'
    | '/(info)/paypal'
    | '/(info)/privacy'
    | '/(info)/roadmap'
    | '/(info)/terms'
    | '/(info)/whatsapp'
    | '/(info)/x'
    | '/(info)/zaio'
    | '/_app/dashboard'
    | '/_app/projects'
    | '/_app/tasks'
    | '/_auth/auth'
    | '/(info)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  infoAboutRoute: typeof infoAboutRoute
  infoContributorsRoute: typeof infoContributorsRoute
  infoCreditRoute: typeof infoCreditRoute
  infoGithubRoute: typeof infoGithubRoute
  infoPaypalRoute: typeof infoPaypalRoute
  infoPrivacyRoute: typeof infoPrivacyRoute
  infoRoadmapRoute: typeof infoRoadmapRoute
  infoTermsRoute: typeof infoTermsRoute
  infoWhatsappRoute: typeof infoWhatsappRoute
  infoXRoute: typeof infoXRoute
  infoZaioRoute: typeof infoZaioRoute
  AuthAuthRoute: typeof AuthAuthRoute
  infoIndexRoute: typeof infoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(info)/': {
      id: '/(info)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof infoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/auth': {
      id: '/_auth/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/(info)/zaio': {
      id: '/(info)/zaio'
      path: '/zaio'
      fullPath: '/zaio'
      preLoaderRoute: typeof infoZaioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(info)/x': {
      id: '/(info)/x'
      path: '/x'
      fullPath: '/x'
      preLoaderRoute: typeof infoXRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(info)/whatsapp': {
      id: '/(info)/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof infoWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(info)/terms': {
      id: '/(info)/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof infoTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(info)/roadmap': {
      id: '/(info)/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof infoRoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(info)/privacy': {
      id: '/(info)/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof infoPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(info)/paypal': {
      id: '/(info)/paypal'
      path: '/paypal'
      fullPath: '/paypal'
      preLoaderRoute: typeof infoPaypalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(info)/github': {
      id: '/(info)/github'
      path: '/github'
      fullPath: '/github'
      preLoaderRoute: typeof infoGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(info)/credit': {
      id: '/(info)/credit'
      path: '/credit'
      fullPath: '/credit'
      preLoaderRoute: typeof infoCreditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(info)/contributors': {
      id: '/(info)/contributors'
      path: '/contributors'
      fullPath: '/contributors'
      preLoaderRoute: typeof infoContributorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(info)/about': {
      id: '/(info)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof infoAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppTasksRoute: typeof AppTasksRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppTasksRoute: AppTasksRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  infoAboutRoute: infoAboutRoute,
  infoContributorsRoute: infoContributorsRoute,
  infoCreditRoute: infoCreditRoute,
  infoGithubRoute: infoGithubRoute,
  infoPaypalRoute: infoPaypalRoute,
  infoPrivacyRoute: infoPrivacyRoute,
  infoRoadmapRoute: infoRoadmapRoute,
  infoTermsRoute: infoTermsRoute,
  infoWhatsappRoute: infoWhatsappRoute,
  infoXRoute: infoXRoute,
  infoZaioRoute: infoZaioRoute,
  AuthAuthRoute: AuthAuthRoute,
  infoIndexRoute: infoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
