/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZaioRouteImport } from './routes/zaio'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LicenseRouteImport } from './routes/license'
import { Route as GithubRouteImport } from './routes/github'
import { Route as ContributorsRouteImport } from './routes/contributors'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareWhatsappRouteImport } from './routes/share.whatsapp'
import { Route as DonatePaypalRouteImport } from './routes/donate.paypal'

const ZaioRoute = ZaioRouteImport.update({
  id: '/zaio',
  path: '/zaio',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LicenseRoute = LicenseRouteImport.update({
  id: '/license',
  path: '/license',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubRoute = GithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributorsRoute = ContributorsRouteImport.update({
  id: '/contributors',
  path: '/contributors',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareWhatsappRoute = ShareWhatsappRouteImport.update({
  id: '/share/whatsapp',
  path: '/share/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const DonatePaypalRoute = DonatePaypalRouteImport.update({
  id: '/donate/paypal',
  path: '/donate/paypal',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contributors': typeof ContributorsRoute
  '/github': typeof GithubRoute
  '/license': typeof LicenseRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/zaio': typeof ZaioRoute
  '/donate/paypal': typeof DonatePaypalRoute
  '/share/whatsapp': typeof ShareWhatsappRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contributors': typeof ContributorsRoute
  '/github': typeof GithubRoute
  '/license': typeof LicenseRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/zaio': typeof ZaioRoute
  '/donate/paypal': typeof DonatePaypalRoute
  '/share/whatsapp': typeof ShareWhatsappRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contributors': typeof ContributorsRoute
  '/github': typeof GithubRoute
  '/license': typeof LicenseRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/zaio': typeof ZaioRoute
  '/donate/paypal': typeof DonatePaypalRoute
  '/share/whatsapp': typeof ShareWhatsappRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contributors'
    | '/github'
    | '/license'
    | '/privacy'
    | '/terms'
    | '/zaio'
    | '/donate/paypal'
    | '/share/whatsapp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contributors'
    | '/github'
    | '/license'
    | '/privacy'
    | '/terms'
    | '/zaio'
    | '/donate/paypal'
    | '/share/whatsapp'
  id:
    | '__root__'
    | '/'
    | '/contributors'
    | '/github'
    | '/license'
    | '/privacy'
    | '/terms'
    | '/zaio'
    | '/donate/paypal'
    | '/share/whatsapp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContributorsRoute: typeof ContributorsRoute
  GithubRoute: typeof GithubRoute
  LicenseRoute: typeof LicenseRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ZaioRoute: typeof ZaioRoute
  DonatePaypalRoute: typeof DonatePaypalRoute
  ShareWhatsappRoute: typeof ShareWhatsappRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zaio': {
      id: '/zaio'
      path: '/zaio'
      fullPath: '/zaio'
      preLoaderRoute: typeof ZaioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/license': {
      id: '/license'
      path: '/license'
      fullPath: '/license'
      preLoaderRoute: typeof LicenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github': {
      id: '/github'
      path: '/github'
      fullPath: '/github'
      preLoaderRoute: typeof GithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contributors': {
      id: '/contributors'
      path: '/contributors'
      fullPath: '/contributors'
      preLoaderRoute: typeof ContributorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/whatsapp': {
      id: '/share/whatsapp'
      path: '/share/whatsapp'
      fullPath: '/share/whatsapp'
      preLoaderRoute: typeof ShareWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate/paypal': {
      id: '/donate/paypal'
      path: '/donate/paypal'
      fullPath: '/donate/paypal'
      preLoaderRoute: typeof DonatePaypalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContributorsRoute: ContributorsRoute,
  GithubRoute: GithubRoute,
  LicenseRoute: LicenseRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ZaioRoute: ZaioRoute,
  DonatePaypalRoute: DonatePaypalRoute,
  ShareWhatsappRoute: ShareWhatsappRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
